

export enum GameActionType {
    ACTIVATE_TOOL = 'ACTIVATE_TOOL',
    DEACTIVATE_TOOL = 'DEACTIVATE_TOOL',
    NEXT_TICK = 'NEXT_TICK',
    ENTER_ROOM = 'ROOM_CHANGED',
    DAY_PASSED = 'DAY_PASSED'
}
