

export enum ActionType {
    UPDATE_USER = 'UPDATE_USER',
    UPDATE_PASSWORD = 'UPDATE_USER',

    LOGIN = 'LOGIN',
    SIGNUP = 'SIGNUP',

    LOGIN_FACEBOOK_REQUEST = 'LOGIN_FACEBOOK_REQUEST',
    LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS',
    LOGIN_FACEBOOK_FAILURE = 'LOGIN_FACEBOOK_FAILURE',

    GET_USER_REQUEST = 'GET_USER_REQUEST',
    GET_USER_SUCCESS = 'GET_USER_SUCCESS',
    GET_USER_FAILURE = 'GET_USER_FAILURE',

    UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE',

    GET_GAME_REQUEST = 'GET_GAME_REQUEST',
    GET_GAME_SUCCESS = 'GET_GAME_SUCCESS',
    GET_GAME_FAILURE = 'GET_GAME_FAILURE'
}
